<?php
require_once('vc-blocks/alert.php');
require_once('vc-blocks/checklist.php');
require_once('vc-blocks/icon_content.php');
require_once('vc-blocks/text-block.php');
require_once('vc-blocks/divider.php');
require_once('vc-blocks/map.php');
require_once('vc-blocks/counter_circle.php');
require_once('vc-blocks/counter_box.php');
require_once('vc-blocks/progress_bar.php');
require_once('vc-blocks/tagline-box.php');
require_once('vc-blocks/audio.php');
require_once('vc-blocks/vimeo.php');
require_once('vc-blocks/youtube.php');
require_once('vc-blocks/button.php');
require_once('vc-blocks/font-awesome.php');
require_once('vc-blocks/post-gallery.php');
require_once('vc-blocks/post-list.php');
require_once('vc-blocks/heading.php');
